name: Build

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-12]

    env:
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      AZURE_SOURCE: ${{ secrets.AZURE_SOURCE }}
      AZURE_USER: ${{ secrets.AZURE_USER }}
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      GITTER_ROOM_ID: ${{ secrets.GITTER_ROOM_ID }}
      GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
      GPR_SOURCE: ${{ secrets.GPR_SOURCE }}
      GPR_USER: ${{ secrets.GPR_USER }}
      GITTER_TOKEN: ${{ secrets.GITTER_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      WYAM_DEPLOY_BRANCH: "gh-pages"
      WYAM_DEPLOY_REMOTE: ${{ github.event.repository.html_url }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
        
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3.1.0
        with:          
          # gitversion needs 5.0 and we need all SDKs the project is targeting
          dotnet-version: |
            3.1.415
            5.0.403
            6.0.100
            7.0.100

      - name: Cache Tools
        uses: actions/cache@v3
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: Build project
        uses: cake-build/cake-action@v1.4.1
        with:
          script-path: recipe.cake
          target: CI
          verbosity: Normal
          cake-version: tool-manifest

      - name: Upload Issues-Report
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: warn
          name: issues
          path: BuildArtifacts/report.html

      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*
